pages/intro/la.tex
pages/intro/probs.tex
pages/intro/python.tex

Small changes on day0 part of the guide:
* 0.2.2 - Added that strings can be surrounded by quotes as well;
* 0.2.2 - Added recommendation for the use of 4 spaces to indent code. Also added reference to PEP8;
* 0.3.3 - Changed notation on L_infinity norm;
* 0.3.4 - Fixed equal signs notation;
* 0.4 - Changed first sentence. Probability is *one* of the mathematical languages for uncertainty and definitely the most used one in ML, if not the only one. However, there are other theories around for dealing with uncertainty. Yes, it is a bit picky of me to change that but the reason I did is to not enrage any mathematicians that might attend the school =);
* 0.4 - "Sample space" -> "A sample space";
* Exercise 0.10 - Changed variable name from CamelCase to words_with_underline spec, to comply …

small changes on day0

---

pages/intro/python.tex

Added a section on basic math operations. Exponentiation is used later in the guide (section 0.2.4) but it is never introduced as being the '**' operator. From my (short) experience, people from non-Python backgrounds usually try to use the '^' operator for exponentiation. This is not only wrong but it is actually the XOR operator in Python, which means it gives unexpected results and adds to the confusion. This section would also be a nice place to explain that '/' means integer division in Python.

added a section on basic math operations

---

pages/intro/no.tex
pages/intro/python.tex

- missing a ')' in intro/python.tex:342
- "the ball will role" -> "the ball will roll" (in intro/no.tex:27)
- gradient_descent (as presented in intro/no.tex:202) should use the given cost/gradient function instead of the globally defined get_y and grad functions -- this should also be corrected in lxmls-toolkit

Small day0 changes

---

pages/sequences/em.tex
pages/sequences/ml.tex

Some tiny naming changes on Day 2, for consistence:
* Section 2.3 (MLE): "Observation Counts" -> "Emission Counts"
* Section 2.7.1 (EM): "node and edge posterior" -> "state and transition posterior"

tiny naming changes

---

pages/sequences/decoding.tex
pages/sequences/hmm.tex
pages/sequences/ml.tex
pages/sequences/pos-induction.tex
pages/sequences/pos.tex

Day 2 is the only part of the guide that adds the python prompt ('>>>') to the environments. I removed all of them to be consistent with the rest of guide. I also added blank lines between the actual outputs of print statements.

removed '>>>' from all python environments in day2

---

pages/parsing/parsing.tex
pages/sequences/pos.tex

- Last year at the summer school I had some trouble with the Eisner algorithm, and I left with the impression that the pseudo-code was a bit off. Today I spent some time on this and found that the variable s should start at 0. On the right complete span, I also used s <= r < t, and then r+1, instead of having s < r <= t and then r, since all the other spans use s <= r < t -- I believe this makes it more legible.
- Fixed a couple of other small typos

Small typos

---

pages/classification/classification.tex

error corected $P(1)=P(2)=P(3)=1/12$ and $P(1)=P(2)=P(3)=1/4$ is not correct.

error in probabilities

---

pages/deep_learning.tex

Just some small fixes on exercise 6.2.
I did have some trouble completing this exercise.
When comparing equations 6.31 and 6.32 with what is in lxmls-toolkit/lxmls/deep_learning/mlp.py, I can't figure out if the code is correct or not:
- when computing nabla_W and nabla_b: the code iterates through the geometry of the network, rather than the training set (like in equations 6.31/32)
- in line 138 it uses $\tilde z^n$ instead of $x^m$ -- although I believe this is a typo in the guide.
The results seem to be good, so the code is likely correct, but I can't see why that would be equivalent.
Also, in equation 6.32, the sum doesn't seem to depend on $m$.

Fixes in exercise 6.2

---

pages/parsing/parsing.tex

A student asked if complete[a,b,c] was the same as complete[a][b][c], in the pseudo-code, since there was mixed notation.

replaced [a][b][c] by [a,b,c]

---

pages/parsing/parsing.tex

As far as I know the language `L = {ab^n aa^n | n ∈ N}` does not correspond to regex `ab* a+`, since there is no way to assure that the number of `a`'s and `b`'s are equal (that is `n`, as the definition states). Consequently, this is also not a language that could be expressed by regular expressions. I believe that what was meant is that these `n`'s are two different numbers, hence I propose the modification.

Corrected regex example in Syntax and Parsing.

---

pages/deep_learning/deep_learning_ff.tex

Fixed some typos, and added some style consistency (e.g. theano -> Theano).
The change from "back-propagation" to "backpropagation" might be controversial; I chose "backpropagation" because that's what Wikipedia uses. Either way, it appeared in both ways, and is now consistent. If we decide "back-propagation" is preferred, I can change to that.

some typos in sections 5.1-5.4

---

pages/deep_learning/deep_learning_ff.tex

This commit corrects
- Expression 5.10 which needs an upper index m on $x_i$
- A couple of F(x, \Theta) for F(xˆm, \Theta)  (are somewhat optional)
- Adds an equation that explains **simply implies computing the average of the gradients for the individual examples**.
We just said
** To simplify notation, and without loss of generality, we will work with the classification cost of an individual example ** 
Then we say that we compute the gradient of the loss (over all the dataset) with respect to W.
We should say gradient of the loss (over the mˆth training point).
Even though expression 5.9 is completely correct without the upper case mˆth I think we should include it (because it is also correct and 
for consistency reasons).

upper indicies stating the mˆth training instance missing

---

pages/deep_learning/deep_learning_ff.tex

One of them was a mispelled ^ character. The other one was missing

missing ^m

---

pages/classification/classification.tex

Max Entropy Batch and online classifiers classes are: MaxEntBatch and MaxEntOnline. In the guide (exercise 1.4), class names have an extra underscore (MaxEnt_Batch and MaxEnt_Online) which does not match the code.
Note: The first PR was incorrect (missing capital letter on Batch/Online)

Fixed PR: Non matching class names for Batch and Online Max Entropy Classifiers.

---

pages/parsing/parsing.tex

Changed the link to visualize parsing trees, as the old one no longer exists (404 error).

Fixed parsing tree visualization link

---

.gitignore
Makefile
pages/classification/classification.tex
pages/intro/la.tex
pages/intro/no.tex
pages/intro/python.tex
pages/seq_discriminative/seq_discriminative.tex
pages/sequences/decoding.tex
pages/sequences/em.tex
pages/sequences/hmm.tex
pages/sequences/ml.tex

This is a simple translation from python2 commands to python3 without any rewrite in the guide text. The text should be revised later. 
obs: Some files were with latin1 characters. My editor by default saved them with utf8.

Converted python commands to python3 compatible

---

pages/reinforcement_learning/reinforcement_learning.tex

It was said in section 6.4 that rewards [10., 2., 3.] are rewards for a
transition into state 1, 2, and 3, respectively.
But such definition and corresponding 'rewards' variable in exercise is
not consistent with code of solution for exercises in lxmls-toolkit,
despite code of solution is correct.
So, here we change definition of 'rewards' variable to make it
consistent with code.
New definition is:
[10., 2., 3.] are expected values of the next reward for each state.
And naturally, for clarity we also introduce actual rewards obtained
after transition to each state.
For more details see corresponding pull request in 'lxmls-toolkit' project:  LxMLS/lxmls-toolkit#130

Fix description of rewards in MRP example in section 6.4 of RL day

---

pages/reinforcement_learning/reinforcement_learning.tex

These changes were accidentally lost because there was a conflict
between two updates in the same paragraph:
(1) Minor text improvements (from PR #125)
(2) Fixing description of rewards (from PR #124)
Change (2) was lost during manual merge.
This commit restores it. Change (1) is also preserved.

Restore changes from pull request #124 lost during manual merge #125

---

pages/deep_learning/deep_learning_ff.tex

Updated logsumexp import for NumpyLogLinear exercise
The example in the guide was not in sync with the code in the
master/student branches. The guide was importing the logsumexp
function from scipy, while the code version uses the LxMLS version
of logsumexp. The latter is the expected behavior, so this commit 
updates the guide version.

Updated logsumexp import for NumpyLogLinear exercise

---

pages/sequences/decoding.tex

Minor typo and removed unicode

---

pages/sequences/pos-induction.tex
pages/sequences/pos.tex
pages/unsupervised/em.tex

Changed all examples of xrange by range and added parenthesis to all examples of print without them.
There is still three instances of xrange in "pages/sequences/decoding.tex" but they are commented, so I decided not to change them.
Solves #143

Removing remmanents of Python 2

---

pages/deep_learning/deep_learning_ff.tex

This change accompanies the two pull requests to the lxmls-toolkit. I did a quick ctrl-F and the `PytorchLogLinear` definition appears to be the only place where `torch.autograd.Variable` occurs.

Remove torch.autograd.Variable from guidebook

---

pages/deep_learning/deep_learning_ff.tex

Dear all,
Thank you for this guide.
This PR fixes the dimensions of `log_tilde_z`. This is according to the up-to-date code in the toolkit repository.

Fix dimensions of `log_tilde_z` in `deep_learning_ff.tex`
